#.travis.yml

language: node_js

dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:9876 &
node_js:
  - "6.9"

jobs:
  include:
    - stage: test
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "sudo chown root /opt/google/chrome/chrome-sandbox"
        - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
        - npm install -g @angular/cli
      script: ng test --single-run
    - stage: build
      before_script: npm install -g @angular/cli
      script: ng-packagr -p ng-package.json

notifications:
  email:
    on_failure: change
    on_success: change
